#!/usr/bin/env perl
use v5.16;
use warnings;

use App;

if ($^O eq "darwin" && $^X eq "/usr/bin/perl") {
    my $lib = "/System/Library/Frameworks/Foundation.framework/Foundation";
    require DynaLoader;
    DynaLoader::dl_load_file $lib;
}

App->new->run(@ARGV);
